---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: rachid135
    password: AFH@jara135
- name: Push to docker hub
  docker_image:
    name: lcangular
    repository: rachid135/jenkins
    tag: latest
    source: local
    push: yes
